sudo: required

language: python

services:
  - docker

script:
  - docker build -t dbarbar/pythonqa:${TRAVIS_COMMIT} .

deploy:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push dbarbar/pythonqa:${TRAVIS_COMMIT}
